name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_test_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Instalar Dependências
        run: npm ci

      - name: Verificação de Código (ESLint)
        run: npm run lint

      - name: Build da Aplicação (Vite)
        run: npm run build

      - name: Deploy para Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_INSTRUTOR_HELVIO }}'
          channelId: live
          projectId: instrutor-helvio
